name: Build

on:
  pull_request:
    branches:
      - '**'

env:
  HUSKY: 0
  VITE_FIREBASE_API_KEY: ${{ secrets.VITE_FIREBASE_API_KEY }}
  VITE_FIREBASE_AUTH_DOMAIN: ${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}
  VITE_FIREBASE_PROJECT_ID: ${{ secrets.VITE_FIREBASE_PROJECT_ID }}
  VITE_FIREBASE_STORAGE_BUCKET: ${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }}
  VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }}
  VITE_FIREBASE_APP_ID: ${{ secrets.VITE_FIREBASE_APP_ID }}
  VITE_FIREBASE_VAPID_KEY: ${{ secrets.VITE_FIREBASE_VAPID_KEY }}
jobs:
   build-check:
    name: Build & Dependency Check
    runs-on: ubuntu-latest
    environment: prod
    permissions:
      contents: read
    steps:
      - name: Check if all Firebase secrets are set
        run: |
          MISSING=0

          check_secret() {
            NAME=$1
            VALUE=$2
            if [ -z "$VALUE" ]; then
              echo "$NAME is not set!"
              MISSING=1
            else
              echo "$NAME is set."
            fi
          }

          check_secret "VITE_FIREBASE_API_KEY" "${{ secrets.VITE_FIREBASE_API_KEY }}"
          check_secret "VITE_FIREBASE_AUTH_DOMAIN" "${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}"
          check_secret "VITE_FIREBASE_PROJECT_ID" "${{ secrets.VITE_FIREBASE_PROJECT_ID }}"
          check_secret "VITE_FIREBASE_STORAGE_BUCKET" "${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }}"
          check_secret "VITE_FIREBASE_MESSAGING_SENDER_ID" "${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }}"
          check_secret "VITE_FIREBASE_APP_ID" "${{ secrets.VITE_FIREBASE_APP_ID }}"
          check_secret "VITE_FIREBASE_VAPID_KEY" "${{ secrets.VITE_FIREBASE_VAPID_KEY }}"

          if [ "$MISSING" -eq 1 ]; then
            echo "One or more Firebase secrets are missing."
            exit 1
          fi

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js and pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Build project
        run: pnpm run build
